/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.JOptionPane;

/**
 *Autores do trabalho:
 * 
 * Nome: Maria Clara Ribeiro de Menezes
 * Matricula: 202165101AC
 * 
 * Nome: Igor Titoneli Almeida
 * Matricula: 202165064AB
 * 
 * Nome: Christian Rafael De Oliveira Coelho
 * Matricula: 202065249AC
 * 
 * Nome: Marlon Ruffo Nascimento
 * Matricula: 202065165AC
 */
public class CadastroBolsa extends javax.swing.JFrame {

    /**
     * Creates new form VisualizaçãoBolsa
     */
    
    public CadastroBolsa() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);

        cadastrar.addActionListener(e -> {
            
            
            
            String titulo = tituloTf.getText();
            int tipo =  tipoBolsaSelect.getSelectedIndex();
            String professor = professorTf.getText();
            String preRequisitos = preRequisitostf.getText();
            String valor = valorTf.getText();
            
            
            if(tipo == 0){
    JOptionPane.showMessageDialog(null, "Por favor, selecione um tipo de bolsa",
            "Aviso", JOptionPane.WARNING_MESSAGE);
                //volta para o programa.
            }
            if (tipo == 1) {
                //Construtor da bolsa MONITORIA
                JOptionPane.showMessageDialog(null, "Bolsa Monitoria cadastrada com sucesso!");
            }
            if (tipo == 2) {
                //Construtor da bolsa Inic.Cientifica
                JOptionPane.showMessageDialog(null, "Bolsa Iniciação Científica cadastrada com sucesso!");
            }
            if (tipo == 3) {
                //Construtor da bolsa Treinamento P.
                JOptionPane.showMessageDialog(null, "Bolsa Treinamento Profissional. cadastrada com sucesso!");
            }
            if (tipo == 4) {
                //Construtor da bolsa Extensão
                JOptionPane.showMessageDialog(null, "Bolsa Extensão cadastrada com sucesso!");
            }
           
            

            tituloTf.setText("");
            tipoBolsaSelect.setSelectedIndex(0);
            professorTf.setText("");
            preRequisitostf.setText("");
            valorTf.setText("");
            
            }
        );
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tituloPrincipal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        professorTf = new javax.swing.JTextField();
        preRequisitostf = new javax.swing.JTextField();
        valorTf = new javax.swing.JTextField();
        cadastrar = new javax.swing.JButton();
        tipoBolsaSelect = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        tituloTf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        metodoEntradaSelect = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cargaHorariaTf1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        qtdVagasSpinner = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 345, 0, 0);

        tituloPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPrincipal.setText("Cadastro de Bolsa");
        tituloPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(tituloPrincipal);
        tituloPrincipal.setBounds(40, 40, 350, 29);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Professor:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 170, 71, 17);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Pré-Requisitos:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 200, 106, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Valor:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 230, 39, 17);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Carga Horária:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 260, 97, 17);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Tipo:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 140, 35, 17);
        getContentPane().add(professorTf);
        professorTf.setBounds(150, 170, 311, 21);
        professorTf.getAccessibleContext().setAccessibleName("");

        preRequisitostf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preRequisitostfActionPerformed(evt);
            }
        });
        getContentPane().add(preRequisitostf);
        preRequisitostf.setBounds(150, 200, 311, 21);

        valorTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorTfActionPerformed(evt);
            }
        });
        getContentPane().add(valorTf);
        valorTf.setBounds(150, 230, 311, 21);

        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrar);
        cadastrar.setBounds(160, 450, 91, 21);

        tipoBolsaSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha", "Monitoria", "Iniciação Científica", "Treinamento Profissional", "Bolsa Extensao" }));
        tipoBolsaSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoBolsaSelectActionPerformed(evt);
            }
        });
        getContentPane().add(tipoBolsaSelect);
        tipoBolsaSelect.setBounds(150, 140, 311, 21);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Título: ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 110, 47, 16);
        jLabel8.getAccessibleContext().setAccessibleName("Título");

        getContentPane().add(tituloTf);
        tituloTf.setBounds(150, 110, 311, 21);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Descrição:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 350, 74, 17);

        metodoEntradaSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha", "Prova", "Entrevista" }));
        metodoEntradaSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodoEntradaSelectActionPerformed(evt);
            }
        });
        getContentPane().add(metodoEntradaSelect);
        metodoEntradaSelect.setBounds(150, 290, 311, 21);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Vagas:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 320, 40, 17);

        cargaHorariaTf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaHorariaTf1ActionPerformed(evt);
            }
        });
        getContentPane().add(cargaHorariaTf1);
        cargaHorariaTf1.setBounds(150, 260, 311, 21);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Método de Entrada:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 290, 137, 17);
        getContentPane().add(qtdVagasSpinner);
        qtdVagasSpinner.setBounds(150, 320, 310, 21);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(150, 350, 310, 91);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preRequisitostfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preRequisitostfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preRequisitostfActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarActionPerformed

    private void tipoBolsaSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoBolsaSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoBolsaSelectActionPerformed

    private void valorTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorTfActionPerformed

    private void metodoEntradaSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodoEntradaSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metodoEntradaSelectActionPerformed

    private void cargaHorariaTf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaHorariaTf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargaHorariaTf1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroBolsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroBolsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroBolsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroBolsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroBolsa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JTextField cargaHorariaTf1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JComboBox<String> metodoEntradaSelect;
    private javax.swing.JTextField preRequisitostf;
    private javax.swing.JTextField professorTf;
    private javax.swing.JSpinner qtdVagasSpinner;
    private javax.swing.JComboBox<String> tipoBolsaSelect;
    private javax.swing.JLabel tituloPrincipal;
    private javax.swing.JTextField tituloTf;
    private javax.swing.JTextField valorTf;
    // End of variables declaration//GEN-END:variables
}
